# Multiclass classification

## Learning objectives

- Understand how classification can be implemented when there are more than 2 classes
- Implement a multiclass classifier from scratch

## Binary vs Multiclass

In binary classification the output must be either `True` or `False` as we already know.

Either the example falls into this class, or it doesn't. We have seen that we can represent this by our model having a single output node whose value is forced between 0 and 1, and as such represents probability that the example belongs to the positive class.

## Multiclass

![](./images/binary-class.jpg)

In the case where we have two nodes to represent true and false, we can think about it as having trained two separate models.

Treating `True` and `False` as separate classes with separate output nodes shows us how we can extend this idea to do multiclass classification; 

> we simply add more nodes and ensure that their values are positive and sum to one.

__Each node is a single `logit` and all of them combined are later passed to `softmax`__

![](./images/multiclass.jpg)

## Multiclass vs Multilabel

In this course we will not talk about __multilabel__ case, but:

> In multilabel problem, each label can exist simultaneously instead of exclusively like in multiclass

This might be a single vector where we have `cat` and `dog` on a picture but not a turtle:

$$
[1, 0, 1]
$$

> In multiclass, __there is always a single `1` label__, not less, not more

## Logits

Here we will also outputs logits, in case of multiclass the only change is __it will be a vector of values__. Each value in the output vector corresponds to certain class.

Let's say we would like to classify our input image into one of threes classes: `{dog=0, cat=1, turtle=2}`. Output of our model might look like this:

$$
    [-5, -3, 2]
$$

This would be a prediction of class `turtle` as it's value is highest.
When we want to get a label from this operation we use [`argmax`](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html):

> argmax returns __index__ of array entry with __the highest value__

As before, we can transform them into probabilities using...

## Softmax

 > The **softmax function** exponentiates each value in a vector to make it positive and then divides each of them by their sum to normalise them (make them sum to 1). 

This ensures that the vector then can be interpreted as a probability distribution.

![](./images/softmax.jpg)

> Real life example with real values

![](./images/softmax_example.jpg)

## Differentiating the softmax

- Softmax derivative is different based on the index of element with respect to which we take derivative. 
- If it is the same as the index of element we applied softmax, the derivative is the equation at the bottom
- Otherwise the one above it. 

![](images/softmax_deriv.jpg)

### Properties of softmax

- increasing the value of any entry decreases the value of all of the others, because the whole vector must always sum to one. 
- an increase in one input element increases it's corresponding output element exponentially whilst pushing others down, 
- this means that __it is very easy for the one largest output element to become dominant__
- because of that `softmax` is overconfident and there are ways to combat this like `label smoothing`

### What does the name "softmax" mean?

- as explained above, usually one input is near `1`, and all others close to `0`. That is, similar to the `argmax` operation mentioned previously but "soft" as it can be differentiated.
- `argmax` changes abruptly, small difference between two values make it either `0` or `1`. Softmax on the other hand changes gradually when the maximum changes

## Exercise

Let's implement our own softmax function.

It should take `x` and divide by `sum` across `axis=1` (as we are normalizing along features):

In [1]:
import numpy as np

def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    exponentials = np.exp(x)
    return exponentials / exponentials.sum(axis=1).reshape(-1, 1)

## Stable softmax

As seen in `sigmoid` case this version also suffers from numerical instability, check out below:

In [2]:
softmax(np.array([[1000, 9, 8], [11, 12, 15]]))

<ipython-input-1-1a709be775cf>:5: RuntimeWarning: overflow encountered in exp
  exponentials = np.exp(x)
<ipython-input-1-1a709be775cf>:6: RuntimeWarning: invalid value encountered in true_divide
  return exponentials / exponentials.sum(axis=1).reshape(-1, 1)


array([[       nan, 0.        , 0.        ],
       [0.01714783, 0.04661262, 0.93623955]])

This time the result is even worse as we get `np.nan` due to overflow. Solution to the problem is to subtract maximum value from each row.

### Subtracting, what?

As `softmax` works along the horizontal axis (`1`) and all values sum to `1` the only thing that matters with the numbers in certain row is their absolute distance. 

This means we can divide __any value__ from them and still get the same results:

In [3]:
original = np.array([5, -2, 0]).reshape(1, -1)
subtracted = original - 6
softmax(original), softmax(subtracted)

(array([[9.92408247e-01, 9.04959183e-04, 6.68679417e-03]]),
 array([[9.92408247e-01, 9.04959183e-04, 6.68679417e-03]]))

### What to subtract?

There is no way to know what is the right `const` value to remove from each row. What if we have `1000` or `1_000_000`? 

Fortunately, we can find maximum in whole batch of data and simply subtract that.

## Exercise

Implement `softmax` function again, this time a stable version:
- subtract `np.max` from `logits` across `1` axis again
- return exponential values calculated this way like previously

Here is our `stable softmax`:

In [4]:
def softmax(logits):
    exps = np.exp(logits - np.max(logits, axis=1).reshape(-1, 1))
    return exps / np.sum(exps, axis=1).reshape(-1, 1)

In [5]:
softmax(np.array([[1000, 9, 8], [11, 12, 15]]))

array([[1.        , 0.        , 0.        ],
       [0.01714783, 0.04661262, 0.93623955]])

## One hot encoding

Our targets can be encoded in multiple ways. Usually, we would simply pass class numbers like this (for `5` samples):

$$
[0, 3, 1, 1, 4]
$$

We could also do that using one-hot encoding:

$$
\begin{align}
&[1, 0, 0, 0, 0]\\
&[0, 0, 0, 1, 0]\\
&[0, 1, 0, 0, 0]\\
&[0, 1, 0, 0, 0]\\
&[0, 0, 0, 0, 1]\\
\end{align}
$$

As most of the data works with the first option, we will now code how to transform `labels` into one-hot-encoding and vice versa:

In [6]:
def to_one_hot(labels, max_labels: int = None):
    if max_labels is None:
        max_labels = np.max(labels) + 1
    return np.eye(max_labels)[labels]


def to_labels(one_hot):
    return np.argmax(one_hot, axis=-1)


data = np.array([0, 1, 0, 3, 5])
to_one_hot(data)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1.]])

## The cross entropy loss function

An appropriate loss function to use for multiclass classification is the __cross entropy loss function__.

- It is a __generalization of binary cross entropy loss__ so it will work in binary case as well
- BCE (binary cross-entropy) is faster and more stable for binary case so __it should be created separately__ and __used separately__.

Like BCE loss, cross entropy uses the same term: __the negative natural log of the output probability__ to penalise outputs exponentially as they stray from the ground truth.

> We don't need to simultaneously push down the incorrect class probabilities and push up the correct class probabilities.

So if we focus on increasing the correct class likelihood element, then we will implicitly be decreasing the incorrect class likelihood elements.

![](images/cross_entropy_loss.jpg)

## Where to use simple linear models?

We have seen how to create and use `linear models` for regression and classification.
Soon we will meet more powerful models but here is the rough summary of when one should use it in real life:
- as a baseline - gives us an overview and "starting point" for improvement
- when we want easily explaianble model. Each weight shows the impact of a factor onto our target
- when we have a lot of features (even more than data point) and we do not want to overfit on data

With experience and more models it will become increasingly clear where we should use each.

## Challenges

- What is the probability for `10` classes to be correctly predicted in __multiclass__ setting? What about __multilabel__ version?
- What loss function should we use when working with multilabel task?
- Code `cross_entropy` only by choosing elements which targets point to. How do we calculate the gradient of the output with respect to the input?
- How does `multiclass` differ from `multilabel`? Show an example for single sample
- Try to implement alpha smoothing. Test on some datasets and check whether that helps on test
- Check out [Don't Overfit II](https://www.kaggle.com/c/dont-overfit-ii) Kaggle challenge and available solution to get a better idea when to use simple models

## Summary

- multiclass classification is multiple linear regression stacked together
- multiclass classification requires a different loss function (cross entropy)
- we can work directly on logits to take predictions by using `argmax`
- softmax is a differentiable function that turns a vector of real numbers into a probability distribution